export const TYPE_OPTIONS = [
  "Technology",
  "Healthcare",
  "Finance & Banking",
  "Education",
  "Retail & E-Commerce",
  "Real Estate",
  "Automotive",
  "Food & Beverage",
  "Fashion & Apparel",
  "Sports & Fitness",
  "Travel & Hospitality",
  "Entertainment & Media",
  "Telecom",
  "Energy & Utilities",
  "Manufacturing",
  "Agriculture",
  "Logistics & Transportation",
  "Construction",
  "Legal Services",
  "Insurance",
  "Pharmaceuticals",
  "Beauty & Personal Care",
  "Home & Furniture",
  "Electronics & Gadgets",
  "Gaming",
  "Non-Profit & NGO",
  "Government & Public Sector",
  "Others",
];
